/********************************************************************************************
* BlueShoes Framework; This file is part of the php application framework.
* NOTE: This code is stripped (obfuscated). To get the clean documented code goto 
*       www.blueshoes.org and register for the free open source *DEVELOPER* version or 
*       buy the commercial version.
*       
*       In case you've already got the developer version, then this is one of the few 
*       packages/classes that is only available to *PAYING* customers.
*       To get it go to www.blueshoes.org and buy a commercial version.
* 
* @copyright www.blueshoes.org
* @author    Samuel Blume <sam at blueshoes dot org>
* @author    Andrej Arn <andrej at blueshoes dot org>
*/
if (typeof(bsWysiwygLang) == 'undefined') bsWyLa = new Array;bsWyLa['btn'] = new Array;bsWyLa['btn']['cut_title']      = 'Cut';bsWyLa['btn']['cut_helpText']   = 'Cut out the selection and put it into the Clipboard.';bsWyLa['btn']['copy_title']     = 'Copy';bsWyLa['btn']['copy_helpText']  = 'Copy the selection and put it into the Clipboard.';bsWyLa['btn']['paste_title']    = 'Paste';bsWyLa['btn']['paste_helpText'] = 'Paste data in clipboard into the current place.';bsWyLa['btn']['undo_title']    = 'Undo';bsWyLa['btn']['undo_helpText'] = 'Undo the last action.';bsWyLa['btn']['redo_title']    = 'Redo';bsWyLa['btn']['redo_helpText'] = 'Redo the previously undone action.';bsWyLa['btn']['bold_title']    = 'Bold';bsWyLa['btn']['bold_helpText'] = 'Makes selected text bold.';bsWyLa['btn']['bold_imgName']  = 'bs_formatBold_en';bsWyLa['btn']['italic_title']    = 'Italic';bsWyLa['btn']['italic_helpText'] = 'Makes selected text italic.';bsWyLa['btn']['italic_imgName']  = 'bs_formatItalic_en';bsWyLa['btn']['underline_title']    = 'Underline';bsWyLa['btn']['underline_helpText'] = 'Unterlines selected text.';bsWyLa['btn']['font_title']    = 'Font';bsWyLa['btn']['font_helpText'] = 'Font';bsWyLa['btn']['forecolor_title']    = 'ForeColor';bsWyLa['btn']['forecolor_helpText'] = 'Sets the foreground (text) color of the current selection.';bsWyLa['btn']['justifyleft_title']    = 'Left';bsWyLa['btn']['justifyleft_helpText'] = 'Aligns the selected paragraphs to the left.';bsWyLa['btn']['justifycenter_title']    = 'Center';bsWyLa['btn']['justifycenter_helpText'] = 'Centers the selected paragraphs.';bsWyLa['btn']['justifyright_title']    = 'Right';bsWyLa['btn']['justifyright_helpText'] = 'Aligns the selected paragraphs to the right.';bsWyLa['btn']['insertorderedlist_title']    = 'Ordered List';bsWyLa['btn']['insertorderedlist_helpText'] = 'Adds numbers to or removes numbers from selected paragraphs.';bsWyLa['btn']['insertunorderedlist_title']    = 'Unordered List';bsWyLa['btn']['insertunorderedlist_helpText'] = 'Adds bullets to or removes bullets from selected paragraphs.';bsWyLa['btn']['outdent_title']    = 'Outdent';bsWyLa['btn']['outdent_helpText'] = 'Outdent text.';bsWyLa['btn']['indent_title']    = 'Indent';bsWyLa['btn']['indent_helpText'] = 'Indent text.';bsWyLa['btn']['createlink_title']    = 'CreateLink';bsWyLa['btn']['createlink_helpText'] = 'CreateLink';bsWyLa['btn']['unlink_title']    = 'UnLink';bsWyLa['btn']['unlink_helpText'] = 'UnLink';bsWyLa['btn']['insertimage_title']    = 'InsertImage';bsWyLa['btn']['insertimage_helpText'] = 'InsertImage';bsWyLa['btn']['specialchars_title']    = 'Special Characters';bsWyLa['btn']['specialchars_helpText'] = 'Pick a special character.';bsWyLa['btn']['inserttable_title']    = 'Insert Table';bsWyLa['btn']['inserttable_helpText'] = 'Insert Table';