<?php/********************************************************************************************
* BlueShoes Framework; This file is part of the php application framework.
* NOTE: This code is stripped (obfuscated). To get the clean documented code goto 
*       www.blueshoes.org and register for the free open source *DEVELOPER* version or 
*       buy the commercial version.
*       
*       In case you've already got the developer version, then this is one of the few 
*       packages/classes that is only available to *PAYING* customers.
*       To get it go to www.blueshoes.org and buy a commercial version.
* 
* @copyright www.blueshoes.org
* @author    Samuel Blume <sam at blueshoes dot org>
* @author    Andrej Arn <andrej at blueshoes dot org>
*/?><?php
define('BS_DOMAININFO_VERSION',      '4.5.$Revision: 1.3 $');if (!@$APP) require_once($_SERVER['DOCUMENT_ROOT'] . $GLOBALS['APP']['path']['diffFromDocRootToGlobalConf'] . 'global.conf.php');require_once($APP['path']['core'] . 'util/Bs_System.class.php');class Bs_DomainInfo extends Bs_Object {var $_Whois;var $cctld;var $tld;var $sld;var $domainInfo;function Bs_DomainInfo($domain) {parent::Bs_Object(); $t = explode('.', $domain);$this->tld = $t[1];$this->sld = $t[0];$this->_Whois = new whois();$this->cacheCctld();}
function go() {reset($this->cctld);while(list($k) = each($this->cctld)) {$this->_checkWhois($this->sld . '.' . $this->cctld[$k]);}
}
function _checkWhois($tld) {$this->domainInfo[$tld]['taken'] = 
$this->domainInfo[$tld]['whois'] = 
}
function _isActive($tld) {$this->domainInfo[$tld]['active'] = 
}
function foo() {$t = array('com', 'net', 'org');}
function cacheCctld() {if (!isSet($this->cctld)) {static $t;$t = array( 
array('country'=>'Afghanistan', 'cctld'=>'af'), 
array('country'=>'Albania', 'cctld'=>'al'), 
array('country'=>'Algeria', 'cctld'=>'dz'), 
array('country'=>'Amcn Samoa', 'cctld'=>'as'), 
array('country'=>'Andorra', 'cctld'=>'ad'), 
array('country'=>'Angola', 'cctld'=>'ao'), 
array('country'=>'Anguilla', 'cctld'=>'ai'), 
array('country'=>'Antarctica', 'cctld'=>'aq'), 
array('country'=>'Antigua', 'cctld'=>'ag'), 
array('country'=>'Argentina', 'cctld'=>'ar'), 
array('country'=>'Armenia', 'cctld'=>'am'), 
array('country'=>'Aruba', 'cctld'=>'aw'), 
array('country'=>'Ascension Is.', 'cctld'=>'ac'), 
array('country'=>'Austria', 'cctld'=>'at'), 
array('country'=>'Australia', 'cctld'=>'au'), 
array('country'=>'Azerbaijan', 'cctld'=>'az'), 
array('country'=>'The Bahamas', 'cctld'=>'bs'), 
array('country'=>'Bahrain', 'cctld'=>'bh'), 
array('country'=>'Bangladesh', 'cctld'=>'bd'), 
array('country'=>'Barbados', 'cctld'=>'bb'), 
array('country'=>'Belarus', 'cctld'=>'by'), 
array('country'=>'Belgium', 'cctld'=>'be'), 
array('country'=>'Belize', 'cctld'=>'bz'), 
array('country'=>'Benin', 'cctld'=>'bj'), 
array('country'=>'Bermuda', 'cctld'=>'bm'), 
array('country'=>'Bhutan', 'cctld'=>'bt'), 
array('country'=>'Bolivia', 'cctld'=>'bo'), 
array('country'=>'Bosnia', 'cctld'=>'ba'), 
array('country'=>'Botswana', 'cctld'=>'bw'), 
array('country'=>'Bouvet Island', 'cctld'=>'bv'), 
array('country'=>'Brazil', 'cctld'=>'br'), 
array('country'=>'British Ind. Oc.(io'), 
array('country'=>'Brunei', 'cctld'=>'bn'), 
array('country'=>'Bulgaria', 'cctld'=>'bg'), 
array('country'=>'Burkina Faso', 'cctld'=>'bf'), 
array('country'=>'Burundi', 'cctld'=>'bi'), 
array('country'=>'Cambodia', 'cctld'=>'kh'), 
array('country'=>'Cameroon', 'cctld'=>'cm'), 
array('country'=>'Canada', 'cctld'=>'ca'), 
array('country'=>'Cape Verde', 'cctld'=>'cv'), 
array('country'=>'Cayman Is.', 'cctld'=>'ky'), 
array('country'=>'Ct. African Rep.(cf'), 
array('country'=>'Chad', 'cctld'=>'td'), 
array('country'=>'C. Is. Guernsey', 'cctld'=>'gg'), 
array('country'=>'C. Is. Jersey', 'cctld'=>'je'), 
array('country'=>'Chile', 'cctld'=>'cl'), 
array('country'=>'China', 'cctld'=>'cn'), 
array('country'=>'Christmas Is.', 'cctld'=>'cx'), 
array('country'=>'Cocos Is.', 'cctld'=>'cc'), 
array('country'=>'Colombia', 'cctld'=>'co'), 
array('country'=>'Comoros', 'cctld'=>'km'), 
array('country'=>'Congo', 'cctld'=>'cg'), 
array('country'=>'Cook Is.', 'cctld'=>'ck'), 
array('country'=>'Costa Rica', 'cctld'=>'cr'), 
array('country'=>"Cote 'Ivoire", 'cctld'=>'ci'), 
array('country'=>'Croatia', 'cctld'=>'hr'), 
array('country'=>'Cuba', 'cctld'=>'cu'), 
array('country'=>'Cyprus', 'cctld'=>'cy'), 
array('country'=>'Czech Rep.', 'cctld'=>'cz'), 
array('country'=>'Denmark', 'cctld'=>'dk'), 
array('country'=>'Djibouti', 'cctld'=>'dj'), 
array('country'=>'Dominica', 'cctld'=>'dm'), 
array('country'=>'Dominican', 'cctld'=>'do'), 
array('country'=>'East Timor', 'cctld'=>'tp'), 
array('country'=>'Ecuador', 'cctld'=>'ec'), 
array('country'=>'Egypt', 'cctld'=>'eg'), 
array('country'=>'El Salvador', 'cctld'=>'sv'), 
array('country'=>'Eq. Guinea', 'cctld'=>'gq'), 
array('country'=>'Eritrea', 'cctld'=>'er'), 
array('country'=>'Estonia', 'cctld'=>'ee'), 
array('country'=>'Ethiopia', 'cctld'=>'et'), 
array('country'=>'Falklands Is.', 'cctld'=>'fk'), 
array('country'=>'Faroe Is.', 'cctld'=>'fo'), 
array('country'=>'Fiji', 'cctld'=>'fj'), 
array('country'=>'Finland', 'cctld'=>'fi'), 
array('country'=>'France', 'cctld'=>'fr'), 
array('country'=>'France, Metro.', 'cctld'=>'fx'), 
array('country'=>'Fr. Guiana', 'cctld'=>'gf'), 
array('country'=>'Fr. Polynesia', 'cctld'=>'pf'), 
array('country'=>'Fr. South.Ter.', 'cctld'=>'tf'), 
array('country'=>'Gabon', 'cctld'=>'ga'), 
array('country'=>'Gambia', 'cctld'=>'gm'), 
array('country'=>'Georgia', 'cctld'=>'ge'), 
array('country'=>'Germany', 'cctld'=>'de'), 
array('country'=>'Ghana', 'cctld'=>'gh'), 
array('country'=>'Gibraltar', 'cctld'=>'gi'), 
array('country'=>'Greece', 'cctld'=>'gr'), 
array('country'=>'Greenland', 'cctld'=>'gl'), 
array('country'=>'Grenada', 'cctld'=>'gd'), 
array('country'=>'Guadeloupe', 'cctld'=>'gp'), 
array('country'=>'Guam', 'cctld'=>'gu'), 
array('country'=>'Guatemala', 'cctld'=>'gt'), 
array('country'=>'Guinea', 'cctld'=>'gn'), 
array('country'=>'Guinea Bissau', 'cctld'=>'gw'), 
array('country'=>'Guyana', 'cctld'=>'gy'), 
array('country'=>'Haiti', 'cctld'=>'ht'), 
array('country'=>'Heard Is.', 'cctld'=>'hm'), 
array('country'=>'Honduras', 'cctld'=>'hn'), 
array('country'=>'Hong Kong', 'cctld'=>'hk'), 
array('country'=>'Hungary', 'cctld'=>'hu'), 
array('country'=>'Iceland', 'cctld'=>'is'), 
array('country'=>'India', 'cctld'=>'in'), 
array('country'=>'Indonesia', 'cctld'=>'id'), 
array('country'=>'Iran', 'cctld'=>'ir'), 
array('country'=>'Iraq', 'cctld'=>'iq'), 
array('country'=>'Ireland', 'cctld'=>'ie'), 
array('country'=>'Isle of Man', 'cctld'=>'im'), 
array('country'=>'Israel', 'cctld'=>'il'), 
array('country'=>'Italy', 'cctld'=>'it'), 
array('country'=>'Jamaica', 'cctld'=>'jm'), 
array('country'=>'Japan', 'cctld'=>'jp'), 
array('country'=>'Jordan', 'cctld'=>'jo'), 
array('country'=>'Kazakhstan', 'cctld'=>'kz'), 
array('country'=>'Kenya', 'cctld'=>'ke'), 
array('country'=>'Kiribati', 'cctld'=>'ki'), 
array('country'=>'Korea, D. Rep.', 'cctld'=>'kp'), 
array('country'=>'Korea, Rep. of', 'cctld'=>'kr'), 
array('country'=>'Kuwait', 'cctld'=>'kw'), 
array('country'=>'Kyrgyzstan', 'cctld'=>'kg'), 
array('country'=>'Laos', 'cctld'=>'la'), 
array('country'=>'Latvia', 'cctld'=>'lv'), 
array('country'=>'Lebanon', 'cctld'=>'lb'), 
array('country'=>'Lesotho', 'cctld'=>'ls'), 
array('country'=>'Liberia', 'cctld'=>'lr'), 
array('country'=>'Libya', 'cctld'=>'ly'), 
array('country'=>'Liechtenstein', 'cctld'=>'li'), 
array('country'=>'Lithuania', 'cctld'=>'lt'), 
array('country'=>'Luxembourg', 'cctld'=>'lu'), 
array('country'=>'Macao', 'cctld'=>'mo'), 
array('country'=>'Macedonia', 'cctld'=>'mk'), 
array('country'=>'Madagascar', 'cctld'=>'mg'), 
array('country'=>'Malawi', 'cctld'=>'mw'), 
array('country'=>'Malaysia', 'cctld'=>'my'), 
array('country'=>'Mali', 'cctld'=>'ml'), 
array('country'=>'Malta', 'cctld'=>'mt'), 
array('country'=>'Marshall Is.', 'cctld'=>'mh'), 
array('country'=>'Martinique', 'cctld'=>'mq'), 
array('country'=>'Mauritania', 'cctld'=>'mr'), 
array('country'=>'Mauritius', 'cctld'=>'mu'), 
array('country'=>'Maldives', 'cctld'=>'mv'), 
array('country'=>'Mayotte', 'cctld'=>'yt'), 
array('country'=>'Mexico', 'cctld'=>'mx'), 
array('country'=>'Micronesia', 'cctld'=>'fm'), 
array('country'=>'Moldova', 'cctld'=>'md'), 
array('country'=>'Monaco', 'cctld'=>'mc'), 
array('country'=>'Mongolia', 'cctld'=>'mn'), 
array('country'=>'Montserrat', 'cctld'=>'ms'), 
array('country'=>'Morocco', 'cctld'=>'ma'), 
array('country'=>'Mozambique', 'cctld'=>'mz'), 
array('country'=>'Myanmar', 'cctld'=>'mm'), 
array('country'=>'Namibia', 'cctld'=>'na'), 
array('country'=>'Nauru', 'cctld'=>'nr'), 
array('country'=>'Nepal', 'cctld'=>'np'), 
array('country'=>'Netherlands', 'cctld'=>'nl'), 
array('country'=>'Neth. Antilles', 'cctld'=>'an'), 
array('country'=>'New Caledonia', 'cctld'=>'nc'), 
array('country'=>'New Zealand', 'cctld'=>'nz'), 
array('country'=>'Nicaragua', 'cctld'=>'ni'), 
array('country'=>'Niger', 'cctld'=>'ne'), 
array('country'=>'Nigeria', 'cctld'=>'ng'), 
array('country'=>'Niue', 'cctld'=>'nu'), 
array('country'=>'Norfolk Is.', 'cctld'=>'nf'), 
array('country'=>'N. Marian. Is.', 'cctld'=>'mp'), 
array('country'=>'Norway', 'cctld'=>'no'), 
array('country'=>'Oman', 'cctld'=>'om'), 
array('country'=>'Pakistan', 'cctld'=>'pk'), 
array('country'=>'Palau', 'cctld'=>'pw'), 
array('country'=>'Panama', 'cctld'=>'pa'), 
array('country'=>'Papua N.G.', 'cctld'=>'pg'), 
array('country'=>'Paraguay', 'cctld'=>'py'), 
array('country'=>'Peru', 'cctld'=>'pe'), 
array('country'=>'Philippines', 'cctld'=>'ph'), 
array('country'=>'Pitcairn', 'cctld'=>'pn'), 
array('country'=>'Poland', 'cctld'=>'pl'), 
array('country'=>'Portugal', 'cctld'=>'pt'), 
array('country'=>'Puerto Rico', 'cctld'=>'pr'), 
array('country'=>'Qatar', 'cctld'=>'qa'), 
array('country'=>'Reunion', 'cctld'=>'re'), 
array('country'=>'Romania', 'cctld'=>'ro'), 
array('country'=>'Russia', 'cctld'=>'ru'), 
array('country'=>'Rwanda', 'cctld'=>'rw'), 
array('country'=>'St. Kitts & Nevis', 'cctld'=>'kn'), 
array('country'=>'Saint Lucia', 'cctld'=>'lc'), 
array('country'=>'St. Vincent', 'cctld'=>'vc'), 
array('country'=>'Samoa', 'cctld'=>'ws'), 
array('country'=>'San Marino', 'cctld'=>'sm'), 
array('country'=>'Sao Tome', 'cctld'=>'st'), 
array('country'=>'Saudi Arabia', 'cctld'=>'sa'), 
array('country'=>'Senegal', 'cctld'=>'sn'), 
array('country'=>'Seychelles', 'cctld'=>'sc'), 
array('country'=>'Sierra Leone', 'cctld'=>'sl'), 
array('country'=>'Singapore', 'cctld'=>'sg'), 
array('country'=>'Slovakia', 'cctld'=>'sk'), 
array('country'=>'Slovenia', 'cctld'=>'si'), 
array('country'=>'Solomon Is.', 'cctld'=>'sb'), 
array('country'=>'Somalia', 'cctld'=>'so'), 
array('country'=>'South Africa', 'cctld'=>'za'), 
array('country'=>'S. Georgia', 'cctld'=>'gs'), 
array('country'=>'Spain', 'cctld'=>'es'), 
array('country'=>'Sri Lanka', 'cctld'=>'lk'), 
array('country'=>'St. Helena', 'cctld'=>'sh'), 
array('country'=>'St. Pierre', 'cctld'=>'pm'), 
array('country'=>'Sudan', 'cctld'=>'sd'), 
array('country'=>'Suriname', 'cctld'=>'sr'), 
array('country'=>'Svalbard', 'cctld'=>'sj'), 
array('country'=>'Swaziland', 'cctld'=>'sz'), 
array('country'=>'Sweden', 'cctld'=>'se'), 
array('country'=>'Switzerland', 'cctld'=>'ch'), 
array('country'=>'Syria', 'cctld'=>'sy'), 
array('country'=>'Taiwan', 'cctld'=>'tw'), 
array('country'=>'Tajikistan', 'cctld'=>'tj'), 
array('country'=>'Tanzania', 'cctld'=>'tz'), 
array('country'=>'Thailand', 'cctld'=>'th'), 
array('country'=>'Togo', 'cctld'=>'tg'), 
array('country'=>'Tokelau', 'cctld'=>'tk'), 
array('country'=>'Tonga', 'cctld'=>'to'), 
array('country'=>'Trinidad', 'cctld'=>'tt'), 
array('country'=>'Tunisia', 'cctld'=>'tn'), 
array('country'=>'Turkey', 'cctld'=>'tr'), 
array('country'=>'Turkmenistan', 'cctld'=>'tm'), 
array('country'=>'Turks & Cai. Is.', 'cctld'=>'tc'), 
array('country'=>'Tuvalu', 'cctld'=>'tv'), 
array('country'=>'Uganda', 'cctld'=>'ug'), 
array('country'=>'Ukraine', 'cctld'=>'ua'), 
array('country'=>'Utd. Arab Em.', 'cctld'=>'ae'), 
array('country'=>'Untd Kingdom', 'cctld'=>'uk'), 
array('country'=>'Untd States', 'cctld'=>'us'), 
array('country'=>'U.S. Minor Is.', 'cctld'=>'um'), 
array('country'=>'Uruguay', 'cctld'=>'uy'), 
array('country'=>'Uzbekistan', 'cctld'=>'uz'), 
array('country'=>'Vanuatu', 'cctld'=>'vu'), 
array('country'=>'Vatican City', 'cctld'=>'va'), 
array('country'=>'Venezuela', 'cctld'=>'ve'), 
array('country'=>'Vietnam', 'cctld'=>'vn'), 
array('country'=>'Virgin Is. Brit.', 'cctld'=>'vg'), 
array('country'=>'Virgin Is. US', 'cctld'=>'vi'), 
array('country'=>'Wallis & Fu. Is.', 'cctld'=>'wf'), 
array('country'=>'Wstn Sahara', 'cctld'=>'eh'), 
array('country'=>'Yemen', 'cctld'=>'ye'), 
array('country'=>'Yugoslavia', 'cctld'=>'yu'), 
array('country'=>'Zaire', 'cctld'=>'zr'), 
array('country'=>'Zambia', 'cctld'=>'zm'), 
array('country'=>'Zimbabwe', 'cctld'=>'zw')
);$this->cctld = &$t;} }
}
?>